/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ChMessage: typeof import('cheetah-design-vue/src/index')['ChMessage']
  const ChNotification: typeof import('cheetah-design-vue/src/index')['ChNotification']
}
